- hosts: localhost
  become: true
  module_defaults:
    group/aws:
      aws_secret_key: ""
      aws_access_key: ""
      region: "ap-south-1"

  tasks:
    - name: "Terminate all running EC2 Instances"
      amazon.aws.ec2_instance:
        state: absent
        filters:
          instance-state-name: running
        
